name       : featherpad
version    : 1.4.1
release    : 6
source     :
    - https://github.com/tsujan/FeatherPad/releases/download/V1.4.1/FeatherPad-1.4.1.tar.xz : f57d7e9392afe3819998049dac1a74528e29728b1132632a2b802c897497e621
license    : GPL-3.0-or-later
component  : office.notes
summary    : FeatherPad is a lightweight Qt plain-text editor for Linux.
description: |
    FeatherPad is a lightweight Qt plain-text editor for Linux.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(hunspell)
    - pkgconfig(x11)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
