name       : featherpad
version    : 1.4.0
release    : 5
source     :
    - https://github.com/tsujan/FeatherPad/releases/download/V1.4.0/FeatherPad-1.4.0.tar.xz : 56d54ff6494a5ebfb628f7a6cabf370d09b9fb6f747b3533abeda6c3d8871671
license    : GPL-3.0-or-later
component  : office.notes
summary    : FeatherPad is a lightweight Qt plain-text editor for Linux.
description: |
    FeatherPad is a lightweight Qt plain-text editor for Linux.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(hunspell)
    - pkgconfig(x11)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
