name       : featherpad
version    : 1.3.4
release    : 3
source     :
    - https://github.com/tsujan/FeatherPad/releases/download/V1.3.4/FeatherPad-1.3.4.tar.xz : 7c0c508a9900193582d8f60af4ec87c23173c73afdf371299bc1e88d8336718b
license    : GPL-3.0-or-later
component  : office.notes
summary    : FeatherPad is a lightweight Qt plain-text editor for Linux.
description: |
    FeatherPad is a lightweight Qt plain-text editor for Linux.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(hunspell)
    - pkgconfig(x11)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
