name       : featherpad
version    : 1.3.5
release    : 4
source     :
    - https://github.com/tsujan/FeatherPad/releases/download/V1.3.5/FeatherPad-1.3.5.tar.xz : 2feec98446d9b37f3735323701a5ee22a8bca7a05ed3d5f884a4245cf06c1dff
license    : GPL-3.0-or-later
component  : office.notes
summary    : FeatherPad is a lightweight Qt plain-text editor for Linux.
description: |
    FeatherPad is a lightweight Qt plain-text editor for Linux.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(hunspell)
    - pkgconfig(x11)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
