name       : featherpad
version    : 0.18.0
release    : 1
source     : 
    - https://github.com/tsujan/FeatherPad/releases/download/V0.18.0/FeatherPad-0.18.0.tar.xz : f95c5494451890eefa7177022b065648b0633d5096715ae7f47c2cc7d784aec8
license    : GPL-3.0-or-later
component  : office.notes
summary    : FeatherPad is a lightweight Qt plain-text editor for Linux.
description: |
    FeatherPad is a lightweight Qt plain-text editor for Linux.
builddeps  :
        - pkgconfig(Qt5Svg)
        - pkgconfig(Qt5X11Extras)
        - pkgconfig(hunspell)
        - pkgconfig(x11)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
