name       : featherpad
version    : 1.1.1
release    : 2
source     :
    - https://github.com/tsujan/FeatherPad/releases/download/V1.1.1/FeatherPad-1.1.1.tar.xz : 90ed9fb3509ce2c5760ac3358e1783d7e2b7d35ee05b48c86d6a2fa25789736d
license    : GPL-3.0-or-later
component  : office.notes
summary    : FeatherPad is a lightweight Qt plain-text editor for Linux.
description: |
    FeatherPad is a lightweight Qt plain-text editor for Linux.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(hunspell)
    - pkgconfig(x11)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
