name       : sakura
version    : 3.8.7
release    : 5
source     :
    - https://launchpad.net/sakura/trunk/3.8.7/+download/sakura-3.8.7.tar.gz : c0feba49d88a039ce56563f43ee59a96fbf9805c02e69775a8fdc45763b8545a
license    : GPL-2.0-or-later
component  : system.utils
summary    : Simple but powerful libvte based terminal emulator
description: |
    Sakura is a terminal emulator and it's only dependencies are GTK and VTE.
builddeps  :
    - pkgconfig(vte-2.91)
    - pkgconfig(xft)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
