name       : sakura
version    : 3.8.6
release    : 4
source     :
    - https://launchpad.net/sakura/trunk/3.8.6/+download/sakura-3.8.6.tar.gz : 8684a215a07fe10405f589e88aee87e0eb8d650134a6f7486c6e5dd9a443de77
license    : GPL-2.0-or-later
component  : system.utils
summary    : Simple but powerful libvte based terminal emulator
description: |
    Sakura is a terminal emulator and it's only dependencies are GTK and VTE.
builddeps  :
    - pkgconfig(vte-2.91)
    - pkgconfig(xft)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
